### ISSUE TITLE
X-NWB/ABF: Clarify support for converting folder of ABF files with differing number of channels

### ISSUE THREAD

**Issue by t-b** [AllenInstitute/ipfx#193]
Data: https://www.dropbox.com/sh/ca0i5vg6fohst8r/AABY8NHXGNxMMjnsdfm-JEMBa?dl=0

When converting the full folder an error is generated:

```
C:\Anaconda2\envs\py36\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to
 `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Converting .
Traceback (most recent call last):
  File "E:/projekte/allensdk.ipfx/ipfx/bin/run_x_to_nwb_conversion.py", line 116, in <module>
    main()
  File "E:/projekte/allensdk.ipfx/ipfx/bin/run_x_to_nwb_conversion.py", line 112, in main
    compression=args.compression)
  File "E:/projekte/allensdk.ipfx/ipfx/bin/run_x_to_nwb_conversion.py", line 58, in convert
    ABFConverter(inFileOrFolder, outFile, outputFeedbackChannel=outputFeedbackChannel, compression=compression)
  File "e:\projekte\allensdk.ipfx\ipfx\x_to_nwb\ABFConverter.py", line 68, in __init__
    self._checkAll()
  File "e:\projekte\allensdk.ipfx\ipfx\x_to_nwb\ABFConverter.py", line 202, in _checkAll
    raise ValueError(f"channelList does not match ({self.refabf.channelList} vs {abf.channelList}.")
ValueError: channelList does not match ([0, 1] vs [0].
(py36)
```
The exception is generated at https://github.com/AllenInstitute/ipfx/blob/c39006c75a586ea992004ed3d45920f31300e7f8/ipfx/x_to_nwb/ABFConverter.py#L198-L204

The reason for that restriction is that we currently generate the list of electrodes in `_createElectrodes` from the list of channels.

Supporting a varying number of channels is easy if we can assume that the channels present in all ABF files are from the same electrode.

**Comment by t-b** [comment]
Answer from Rene Wilbers:

> Regards to *0005: Indeed, the missing of the feedback channel is a mistake, although I think it probably occurs only in the bridge balance test pulse protocol. Regarding *0004, indeed sometimes the same channel is saved with a different name. I can confirm that for files with the channel name '_Ipatch' the correct name should be 'IN0'. There should also be some additional info in the abf file (the stringsection), where information is stored on the DAC numbers of the channels. If you could extract that, the best way would be to create a new channel name: 'IN{DAC number}'
