### ISSUE TITLE
DAT data with stimulus reconstruction issues

### ISSUE THREAD

**Issue by t-b** [AllenInstitute/ipfx#199]
From https://ai-mies.slack.com/archives/DB81GAXL5/p1553719273000100?thread_ts=1553208910.001000&cid=DB81GAXL5.

I can't get the NaN error.

Here is what I did:

```
# fetch protocols from the  tests
e/projekte/allensdk.ipfx/tests (master)
$ py.test.exe --collect-only --do-x-nwb-tests test_x_nwb.py
# download and extract file DAT file
$ ../ipfx/bin/run_x_to_nwb_conversion.py --fileType ".abf" --protocolDir ../tests/reference_atf .
```

and this gets me 

```
$ ../ipfx/bin/run_x_to_nwb_conversion.py --fileType ".abf" --protocolDir ../tests/reference_atf .
C:\Anaconda2\envs\py36\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to
 `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Converting .
Traceback (most recent call last):
  File "../ipfx/bin/run_x_to_nwb_conversion.py", line 128, in <module>
    main()
  File "../ipfx/bin/run_x_to_nwb_conversion.py", line 124, in main
    compression=args.compression)
  File "../ipfx/bin/run_x_to_nwb_conversion.py", line 60, in convert
    ABFConverter(inFileOrFolder, outFile, outputFeedbackChannel=outputFeedbackChannel, compression=compression)
  File "e:\projekte\allensdk.ipfx\ipfx\x_to_nwb\ABFConverter.py", line 71, in __init__
    self._checkAll()
  File "e:\projekte\allensdk.ipfx\ipfx\x_to_nwb\ABFConverter.py", line 232, in _checkAll
    raise ValueError(f"channelList does not match ({self.refabf.channelList} vs {abf.channelList}).")
ValueError: channelList does not match ([0, 1] vs [0]).
(py36)
```

which does not work, reported in #192, but does not give a NAN error here.

**Comment by t-b** [comment]
Commit: `01263ff3 (Merge pull request #196 from t-b/folder-watch-mode, 2019-03-26)`

**Comment by t-b** [comment]
Not reproducible. Closing for now.
