### ISSUE TITLE
Ipfx fails to build because of dependency in pyABF

### ISSUE THREAD

**Issue by sgratiy** [AllenInstitute/ipfx#322]
pyABF is trying to import numpy in the setup.py read during dependency collection. Thus fails the import

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-2184ovzy/pyabf/setup.py", line 3, in <module>
        import pyabf
      File "/tmp/pip-install-2184ovzy/pyabf/pyabf/__init__.py", line 18, in <module>
        from pyabf.abf import ABF
      File "/tmp/pip-install-2184ovzy/pyabf/pyabf/abf.py", line 10, in <module>
        import pyabf.abfWriter
      File "/tmp/pip-install-2184ovzy/pyabf/pyabf/abfWriter.py", line 14, in <module>
        import numpy as np
    ModuleNotFoundError: No module named 'numpy'

**Comment by t-b** [comment]
It think this is fixed since https://github.com/swharden/pyABF/pull/104.
