### ISSUE TITLE
Ephys NWB "Shapes do not match" error in feature extraction

### ISSUE THREAD

**Issue by wbwakeman** [AllenInstitute/ipfx#404]
Running ipfx feature extraction on ephys data for June about 90% fail with this error:

```
Traceback (most recent call last):
  File "/allen/aibs/technology/waynew/conda/ipfx37_dev/lib/python3.7/site-packages/ipfx/bin/run_pipeline_from_nwb_file.py", line 59, in <module>
    main()
  File "/allen/aibs/technology/waynew/conda/ipfx37_dev/lib/python3.7/site-packages/ipfx/bin/run_pipeline_from_nwb_file.py", line 53, in main
    pipeline_input["manual_sweep_states"])
  File "/allen/aibs/technology/waynew/conda/ipfx37_dev/lib/python3.7/site-packages/ipfx/bin/run_pipeline.py", line 59, in run_pipeline
    se_output['cell_features'],
  File "/allen/aibs/technology/waynew/conda/ipfx37_dev/lib/python3.7/site-packages/ipfx/bin/run_feature_extraction.py", line 74, in run_feature_extraction
    output_nwb_path=output_nwb_file)
  File "/allen/aibs/technology/waynew/conda/ipfx37_dev/lib/python3.7/site-packages/ipfx/nwb_append.py", line 61, in append_spike_times
    nwb_io.write(nwbfile)
  File "/allen/aibs/technology/waynew/conda/ipfx37_dev/lib/python3.7/site-packages/hdmf/utils.py", line 483, in func_call
    return func(args[0], **parsed['args'])
  File "/allen/aibs/technology/waynew/conda/ipfx37_dev/lib/python3.7/site-packages/hdmf/backends/hdf5/h5tools.py", line 297, in write
    ns_builder.export('namespace', writer=writer)
  File "/allen/aibs/technology/waynew/conda/ipfx37_dev/lib/python3.7/site-packages/hdmf/utils.py", line 483, in func_call
    return func(args[0], **parsed['args'])
  File "/allen/aibs/technology/waynew/conda/ipfx37_dev/lib/python3.7/site-packages/hdmf/spec/write.py", line 213, in export
    writer.write_spec(out, path)
  File "/allen/aibs/technology/waynew/conda/ipfx37_dev/lib/python3.7/site-packages/hdmf/backends/hdf5/h5_utils.py", line 280, in write_spec
    return self.__write(spec, path)
  File "/allen/aibs/technology/waynew/conda/ipfx37_dev/lib/python3.7/site-packages/hdmf/backends/hdf5/h5_utils.py", line 276, in __write
    dset = self.__group.require_dataset(name, shape=tuple(), data=data, dtype=self.__str_type)
  File "/allen/aibs/technology/waynew/conda/ipfx37_dev/lib/python3.7/site-packages/h5py/_hl/group.py", line 198, in require_dataset
    raise TypeError("Shapes do not match (existing %s vs new %s)" % (dset.shape, shape))
TypeError: Shapes do not match (existing (1,) vs new ())
```

Running this with a test file at:
/allen/aibs/technology/waynew/ephys/features/troubleshoot_392647.05.02.01/dev.pbs

**Comment by MatthewAitken** [comment]
created an issue here: https://github.com/NeurodataWithoutBorders/pynwb/issues/1228
